# Generated by Django 3.0.7 on 2020-11-10 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectProduct', to='product.Product', verbose_name='收藏商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectUser', to=settings.AUTH_USER_MODEL, verbose_name='收藏人')),
            ],
            options={
                'verbose_name': '收藏',
                'db_table': 'collect',
            },
        ),
    ]
