# Generated by Django 3.0.7 on 2020-11-10 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.tests


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producclassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='商品分类名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentClassify', to='product.Producclassify', verbose_name='商品上级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'db_table': 'product_classify',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('product_name', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('Product_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='商品简介')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('product_stock', models.IntegerField(default=1, verbose_name='商品库存')),
                ('product_sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('product_is_putaway', models.BooleanField(default=False, verbose_name='是否发布商品中心')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createUser', to=settings.AUTH_USER_MODEL, verbose_name='创建管理员')),
                ('product_classify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='product.Producclassify')),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image_url', models.ImageField(blank=True, upload_to=product.tests.get_image_path, verbose_name='图片路由')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='product.Product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'db_table': 'product_images',
            },
        ),
    ]
