# Generated by Django 3.0.7 on 2020-11-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producclassify',
            new_name='ProductClassify',
        ),
    ]
